"""
GithubTool: Opens a Pull Request on GitHub for a ScopeSentinel-generated branch.

Reads configuration from environment variables:
  - GITHUB_TOKEN:       Personal access token (repo + PR scope)
  - GITHUB_REPO_OWNER:  GitHub org/username
  - GITHUB_REPO_NAME:   Repository name
  - JIRA_URL:           Base Jira URL (for linking the ticket in the PR body)
"""

import logging
import os
from dataclasses import dataclass

from dotenv import load_dotenv
from github import Github, GithubException

from agents.planner_agent import PlannerOutput
from tools.jira_tool import JiraTicket

logger = logging.getLogger(__name__)


@dataclass
class PRResult:
    """Result of a GitHub pull request creation."""
    pr_number: int
    pr_url: str
    title: str


def _build_pr_body(ticket: JiraTicket, plan: PlannerOutput, jira_url: str) -> str:
    """Construct a rich PR description from the ticket and approved plan."""
    ticket_url = f"{jira_url.rstrip('/')}/browse/{ticket.id}"

    steps_md = "\n".join(f"{i}. {s}" for i, s in enumerate(plan.steps, 1))

    return f"""\
## 🎫 Jira Ticket
**[{ticket.id}]({ticket_url})** — {ticket.summary}

---

## 📐 Architecture Notes
{plan.architecture_notes or "_None provided._"}

---

## 📋 Implementation Steps
{steps_md or "_No steps recorded._"}

---

> _This PR was automatically generated by [ScopeSentinel](https://github.com) \
and approved by a human reviewer via the HITL gateway._
"""


class GithubTool:
    """
    Opens a GitHub Pull Request for a given sentinel branch.
    """

    def __init__(self):
        load_dotenv()
        self.token      = os.environ.get("GITHUB_TOKEN", "")
        self.repo_owner = os.environ.get("GITHUB_REPO_OWNER", "")
        self.repo_name  = os.environ.get("GITHUB_REPO_NAME", "")
        self.jira_url   = os.environ.get("JIRA_URL", "")

        if not all([self.token, self.repo_owner, self.repo_name]):
            raise EnvironmentError(
                "Missing GitHub config. Please set GITHUB_TOKEN, GITHUB_REPO_OWNER, "
                "and GITHUB_REPO_NAME in your .env file."
            )

        from github import Auth
        self._client = Github(auth=Auth.Token(self.token))
        self._gh_repo = self._client.get_repo(f"{self.repo_owner}/{self.repo_name}")
        logger.info(f"GithubTool: connected to {self.repo_owner}/{self.repo_name}")

    def create_pr(
        self,
        ticket: JiraTicket,
        plan: PlannerOutput,
        branch_name: str,
        base_branch: str = "main",
    ) -> PRResult:
        """
        Create a Pull Request from sentinel branch → base branch.

        Args:
            ticket:       The original Jira ticket.
            plan:         The approved PlannerOutput.
            branch_name:  The sentinel branch to merge from (e.g. "sentinel/SCRUM-6").
            base_branch:  The target branch (default: "main").

        Returns:
            A PRResult with pr_number, pr_url, and title.

        Raises:
            ValueError: If PR creation fails.
        """
        title = f"[{ticket.id}] {ticket.summary}"
        body  = _build_pr_body(ticket, plan, self.jira_url)

        try:
            pr = self._gh_repo.create_pull(
                title=title,
                body=body,
                head=branch_name,
                base=base_branch,
            )
            logger.info(f"GithubTool: PR #{pr.number} created → {pr.html_url}")
            return PRResult(
                pr_number=pr.number,
                pr_url=pr.html_url,
                title=title,
            )
        except GithubException as e:
            # Handle "PR already exists" gracefully
            if e.status == 422 and any(
                "already exists" in str(err.get("message", ""))
                for err in e.data.get("errors", [])
            ):
                logger.warning("GithubTool: PR already exists for this branch.")
                # Find and return the existing PR
                prs = list(self._gh_repo.get_pulls(head=f"{self.repo_owner}:{branch_name}"))
                if prs:
                    existing = prs[0]
                    return PRResult(
                        pr_number=existing.number,
                        pr_url=existing.html_url,
                        title=existing.title,
                    )
            raise ValueError(f"Failed to create PR: {e.data}") from e
