"""Alembic migration script template.

Revision ID: 4914389497a3
Revises: 005
Create Date: 2026-04-11 22:49:09.800027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4914389497a3'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by', sa.Enum('MANUAL', 'WORKFLOW', 'TRIGGER', name='agentruntriggeredby', native_enum=False), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skill_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_app_connections',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'connection_id')
    )

    op.add_column('agents', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('agents', sa.Column('timeout_seconds', sa.Integer(), nullable=False, server_default='60'))
    op.add_column('agents', sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', 'ARCHIVED', name='agentstatus', native_enum=False), nullable=False, server_default='DRAFT'))
    op.drop_index(op.f('ix_agents_is_active'), table_name='agents')
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.drop_column('agents', 'tools_json')
    op.drop_column('agents', 'max_iterations')
    op.drop_column('agents', 'identity')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'memory_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('memory_mode', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('identity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('max_iterations', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('tools_json', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.create_index(op.f('ix_agents_is_active'), 'agents', ['is_active'], unique=False)
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'timeout_seconds')
    op.drop_column('agents', 'instructions')

    op.drop_table('agent_app_connections')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
