"""Alembic migration script template.

Revision ID: 4914389497a3
Revises: 005
Create Date: 2026-04-11 22:49:09.800027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4914389497a3'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by', sa.Enum('MANUAL', 'WORKFLOW', 'TRIGGER', name='agentruntriggeredby', native_enum=False), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skill_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_app_connections',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['oauth_connections.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'connection_id')
    )
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_occurred_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_org_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_org_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_usage_buckets_org_id'), table_name='usage_buckets')
    op.drop_index(op.f('ix_usage_buckets_period_start'), table_name='usage_buckets')
    op.drop_table('usage_buckets')
    op.drop_index(op.f('ix_tenant_provision_logs_org_id'), table_name='tenant_provision_logs')
    op.drop_table('tenant_provision_logs')
    op.add_column('agents', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('agents', sa.Column('timeout_seconds', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', 'ARCHIVED', name='agentstatus', native_enum=False), nullable=False))
    op.drop_index(op.f('ix_agents_is_active'), table_name='agents')
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.drop_column('agents', 'tools_json')
    op.drop_column('agents', 'max_iterations')
    op.drop_column('agents', 'identity')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'memory_mode')
    op.alter_column('hitl_events', 'action',
               existing_type=postgresql.ENUM('APPROVE', 'REJECT', 'MODIFY', name='hitlaction'),
               type_=sa.Enum('APPROVE', 'REJECT', 'MODIFY', name='hitlaction', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key(None, 'hitl_events', 'workflow_runs', ['run_id'], ['id'])
    op.alter_column('orgs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PROVISIONING', 'ACTIVE', 'SUSPENDED', 'DEPROVISIONED', name='tenantstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('orgs', 'tenant_config',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('orgs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_orgs_status'), 'orgs', ['status'], unique=False)
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_orgs_status'), table_name='orgs')
    op.alter_column('orgs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orgs', 'tenant_config',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orgs', 'status',
               existing_type=sa.Enum('PROVISIONING', 'ACTIVE', 'SUSPENDED', 'DEPROVISIONED', name='tenantstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(None, 'hitl_events', type_='foreignkey')
    op.alter_column('hitl_events', 'action',
               existing_type=sa.Enum('APPROVE', 'REJECT', 'MODIFY', name='hitlaction', native_enum=False),
               type_=postgresql.ENUM('APPROVE', 'REJECT', 'MODIFY', name='hitlaction'),
               existing_nullable=False)
    op.add_column('agents', sa.Column('memory_mode', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('identity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('max_iterations', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('tools_json', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.create_index(op.f('ix_agents_is_active'), 'agents', ['is_active'], unique=False)
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'timeout_seconds')
    op.drop_column('agents', 'instructions')
    op.create_table('tenant_provision_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('tenant_provision_logs_org_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_provision_logs_pkey'))
    )
    op.create_index(op.f('ix_tenant_provision_logs_org_id'), 'tenant_provision_logs', ['org_id'], unique=False)
    op.create_table('usage_buckets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('runs_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steps_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('llm_calls_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_buckets_pkey'))
    )
    op.create_index(op.f('ix_usage_buckets_period_start'), 'usage_buckets', ['period_start'], unique=False)
    op.create_index(op.f('ix_usage_buckets_org_id'), 'usage_buckets', ['org_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload_json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_org_id'), 'audit_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_events_pkey'))
    )
    op.create_index(op.f('ix_usage_events_org_id'), 'usage_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_usage_events_occurred_at'), 'usage_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.drop_table('agent_app_connections')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
