"""Alembic migration script template.

Revision ID: ccd0290433c9
Revises: 5b079f4c0351
Create Date: 2026-03-24 10:59:33.227820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd0290433c9'
down_revision: Union[str, None] = '5b079f4c0351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_connections_org_id'), 'oauth_connections', ['org_id'], unique=False)
    op.create_index(op.f('ix_oauth_connections_provider'), 'oauth_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_provider'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_org_id'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    # ### end Alembic commands ###
