"""Alembic migration script template.

Revision ID: b24d946fd230
Revises: 003
Create Date: 2026-03-21 15:52:58.245181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b24d946fd230'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installed_connectors', 'config_json',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('run_steps', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('run_steps', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('run_steps', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('run_steps', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('workflow_runs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('estimated_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'estimated_cost')
    op.drop_column('workflow_runs', 'completion_tokens')
    op.drop_column('workflow_runs', 'prompt_tokens')
    op.drop_column('workflow_runs', 'total_tokens')
    op.drop_column('run_steps', 'estimated_cost')
    op.drop_column('run_steps', 'completion_tokens')
    op.drop_column('run_steps', 'prompt_tokens')
    op.drop_column('run_steps', 'total_tokens')
    op.alter_column('installed_connectors', 'config_json',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
