"""Alembic migration script template.

Revision ID: e42dc3df3b12
Revises: ccd0290433c9
Create Date: 2026-03-24 11:21:37.286059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e42dc3df3b12'
down_revision: Union[str, None] = 'ccd0290433c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_connections', sa.Column('provider_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_connections', 'provider_metadata')
    # ### end Alembic commands ###
